Feature/update expression
psrenergy/PSRIO-base pull request #2
Opened 2023-08-18 12:55 UTC by Iurysab

2023-08-20 18:10 UTC, raphasampaio requested changes

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +                goto stg_found
we should not use the goto command

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +    for _,agent in ipairs(agents) do
use the syntax formatter

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +        if (string.sub(agent, 1, lenth_str) == str) then
don't need these parenthesis

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +    return self:select_agents(found_agents)
there are some missing ;

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +    local vec_selc_stag = {};
keep the variables names expanded, example: vec_selc_stag -> selected_stages

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +            if( stg == stg_v ) then
don't need these parenthesis

2023-08-20 18:10 UTC, raphasampaio commented on extensions/expression.lua
> +    N_scn = self:scenarios();
use local and expanded names

2023-08-22 15:06 UTC, Iurysab commented on extensions/expression.lua
> +                goto stg_found
done

2023-08-22 15:08 UTC, Iurysab commented on extensions/expression.lua
> +        if (string.sub(agent, 1, lenth_str) == str) then
done

2023-08-22 15:08 UTC, Iurysab commented on extensions/expression.lua
> +    for _,agent in ipairs(agents) do
done

2023-08-22 15:10 UTC, Iurysab commented on extensions/expression.lua
> +        if (string.sub(agent, 1, lenth_str) == str) then
done

2023-08-22 15:12 UTC, Iurysab commented on extensions/expression.lua
> +    return self:select_agents(found_agents)
done

2023-08-23 19:10 UTC, merged